### ISSUE TITLE
Unable to use the package | Non-static method printers() cannot be called statically

### ISSUE THREAD

**Issue by MuhammadAbbasAkhtar** [rawilk/laravel-printing#25]
I have installed this package on a fresh installation, completed all the steps from the Docs. Using CUPS and getting this error
`Non-static method Rawilk\Printing\Printing::printers() cannot be called statically`

I have setup the cups server info in the env and the server is accessible from browser. 

I tried using it like this `$printer = (new Printing)->printers();` and got this error `Too few arguments to function Rawilk\Printing\Printing::__construct()`

**Comment by cntabana** [comment]
_I have installed this package on a fresh installation, completed all the steps from the Docs. Using CUPS and getting this error
Non-static method Rawilk\Printing\Printing::printers() cannot be called statically_

Make sure you import facade instead of the printing class.
using this namespace **use Rawilk\Printing\Facades\Printing** instead of this one  use Rawilk\Printing

**Comment by rawilk** [comment]
@cntabana is correct. Make sure you're using the facade.
